services:
  database:
    image: postgres:16-alpine
    container_name: ${container_name}
    env_file: .env
    environment:
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_DB: ${db_name}
    ports:
      - '${db_port}:${db_port}'
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
